<div class="home-teaser-wrapper">
    <div class="home-teaser">
        <div class="home-teaser-video">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/nO-R88V2cbw?si=N8JG46XZ7Ryh3ee0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
        <div class="home-teaser-text">
            <p><?php echo __('home-teaser-line-1') ?></p>
            <p><?php echo __('home-teaser-line-2') ?></p>
            <p><?php echo __('home-teaser-line-3') ?></p>
        </div>
    </div>
</div>
